import { Plus_Jakarta_Sans, Damion } from "next/font/google";
import "./globals.css";
import { Navbar, Footer } from "../components";
import clsx from "clsx";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-sans",
});
const damion = Damion({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-damion",
});

export const metadata = {
  title: "Abby n Bev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${plusJakarta.variable} ${damion.variable}`}>
      <body className="font-sans bg-[#f7f7f7]">
        <Navbar />
        <main> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
